package eu.choreos.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-11T16:07:14.484-03:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SM1", 
                  wsdlLocation = "file:SM1.wsdl",
                  targetNamespace = "http://services.choreos.eu/") 
public class SM1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.choreos.eu/", "SM1");
    public final static QName SM1Port = new QName("http://services.choreos.eu/", "SM1Port");
    static {
        URL url = null;
        try {
            url = new URL("file:SM1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SM1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:SM1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SM1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SM1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SM1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SM1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SM1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SM1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SM1PortType
     */
    @WebEndpoint(name = "SM1Port")
    public SM1PortType getSM1Port() {
        return super.getPort(SM1Port, SM1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SM1PortType
     */
    @WebEndpoint(name = "SM1Port")
    public SM1PortType getSM1Port(WebServiceFeature... features) {
        return super.getPort(SM1Port, SM1PortType.class, features);
    }

}
