package eu.choreos.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-11T16:07:17.993-03:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SM3", 
                  wsdlLocation = "file:SM3.wsdl",
                  targetNamespace = "http://services.choreos.eu/") 
public class SM3 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.choreos.eu/", "SM3");
    public final static QName SM3Port = new QName("http://services.choreos.eu/", "SM3Port");
    static {
        URL url = null;
        try {
            url = new URL("file:SM3.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SM3.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:SM3.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SM3(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SM3(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SM3() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SM3(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SM3(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SM3(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SM3PortType
     */
    @WebEndpoint(name = "SM3Port")
    public SM3PortType getSM3Port() {
        return super.getPort(SM3Port, SM3PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SM3PortType
     */
    @WebEndpoint(name = "SM3Port")
    public SM3PortType getSM3Port(WebServiceFeature... features) {
        return super.getPort(SM3Port, SM3PortType.class, features);
    }

}
