
package eu.choreos.services;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-11T16:07:19.735-03:00
 * Generated source version: 2.4.1
 * 
 */
 
public class SM4PortType_SM4Port_Server{

    protected SM4PortType_SM4Port_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SM4PortTypeImpl();
        String address = "http://localhost:4321/WS/SM4";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SM4PortType_SM4Port_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
