
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package eu.choreos.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-11T16:07:23.119-03:00
 * Generated source version: 2.4.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SM6",
                      portName = "SM6Port",
                      targetNamespace = "http://services.choreos.eu/",
                      wsdlLocation = "file:SM6.wsdl",
                      endpointInterface = "eu.choreos.services.SM6PortType")
                      
public class SM6PortTypeImpl implements SM6PortType {

    private static final Logger LOG = Logger.getLogger(SM6PortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see eu.choreos.services.SM6PortType#getPrice(java.lang.String  arg0 )*
     */
    public double getPrice(java.lang.String arg0) { 
        LOG.info("Executing operation getPrice");
        System.out.println(arg0);
        try {
            double _return = SM6Data.getPrice(arg0);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
