package eu.choreos.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-11T16:07:23.145-03:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://services.choreos.eu/", name = "SM6PortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SM6PortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://services.choreos.eu/", className = "eu.choreos.services.GetPrice")
    @WebMethod
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://services.choreos.eu/", className = "eu.choreos.services.GetPriceResponse")
    public double getPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
