<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:processDefinition="http://petals.ow2.org/bpel/futureMart/" xmlns:tns="http://petals.ow2.org/bpel/futureMart/Artifacts" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://services.choreos.eu/" xmlns:wsdl1="http://smregistry.choreos.eu" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="futureMartArtifacts" targetNamespace="http://petals.ow2.org/bpel/futureMart/Artifacts">
		
  
    <plnk:partnerLinkType name="futureMartPT">
    <plnk:role name="futureMartWSRole" portType="wsdl:FutureMartWS"/>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="orchestratorPT">
    <plnk:role name="orchestratorRole" portType="processDefinition:futureMartPortType"/>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="smRegistryPT">
    <plnk:role name="smRegistryRole" portType="wsdl1:SMRegistryWS"/>
  </plnk:partnerLinkType>
    <import location="futureMartWS.wsdl" namespace="http://services.choreos.eu/"/>
    <import location="futureMartDefinition.wsdl" namespace="http://petals.ow2.org/bpel/futureMart/"/>
    <import location="smregistry.wsdl" namespace="http://smregistry.choreos.eu"/>
</definitions>
