<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:processDefinition="http://petals.ow2.org/bpel/Shipper1/" xmlns:tns="http://petals.ow2.org/bpel/Shipper1/Artifacts" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://services.choreos.eu/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Shipper1Artifacts" targetNamespace="http://petals.ow2.org/bpel/Shipper1/Artifacts">
		
    <plnk:partnerLinkType name="Shipper1PLT">
        <plnk:role name="Shipper1Role" portType="processDefinition:Shipper1PortType"/>
    </plnk:partnerLinkType>
  
    <plnk:partnerLinkType name="shipperWSPT">
    <plnk:role name="shipperWSRole" portType="wsdl:ShipperWS"/>
  </plnk:partnerLinkType>
    <import location="Shipper1Definition.wsdl" namespace="http://petals.ow2.org/bpel/Shipper1/"/>
    <import location="shipperWS.wsdl" namespace="http://services.choreos.eu/"/>
</definitions>
